### ISSUE TITLE
Error when starting circus

### ISSUE THREAD

**Issue by njordr** [circus-tent/circus#1026]
Hi.

I follow the tutorial at this page: https://circus.readthedocs.io/en/latest/tutorial/step-by-step/

When I start circus:
circusd etc/circus.ini

I've got this exceptions:
2017-02-23 13:25:45 [18854] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/venv/circus/lib/python3.5/site-packages/circusweb/circushttpd.py", line 25, in <module>
    import tornadio2
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/__init__.py", line 25, in <module>
    from tornadio2.router import TornadioRouter
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/router.py", line 27, in <module>
    from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/persistent.py", line 143
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
2017-02-23 13:25:45 circus[18856] [INFO] Starting the stats streamer
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/venv/circus/lib/python3.5/site-packages/circusweb/circushttpd.py", line 25, in <module>
    import tornadio2
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/__init__.py", line 25, in <module>
    from tornadio2.router import TornadioRouter
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/router.py", line 27, in <module>
    from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
  File "/opt/venv/circus/lib/python3.5/site-packages/tornadio2/persistent.py", line 143
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

**Comment by k4nar** [comment]
I think you trying to use Circusweb, but it's not compatible with Python 3. Circusweb is not really maintained, so I wouldn't advise to use it.

**Comment by njordr** [comment]
Thanks
