### ISSUE TITLE
Hooks are not passed the same environment as their watcher

### ISSUE THREAD

**Issue by corydodt** [circus-tent/circus#1040]
Seems simple enough; hooks that need to use the same variables as exist in the watcher's environment cannot do so.

```
# circus.ini
[watcher:hello]
cmd: true
hooks.before_start: hello.hook

[env:hello]
hello_env: world
```
```
# hello.py
def hook(watcher, arbiter, hook_name):
    import os
    print os.environ['hello_env']
```

After running: `circusd circus.ini` I get the following output:
```
% circusd circus.ini
2017-05-14 13:15:56 circus[22707] [INFO] Starting master on pid 22707
2017-05-14 13:15:56 circus[22707] [ERROR] Hook 'before_start' failed
Traceback (most recent call last):
  File "/home/cory/.virtualenvs/noms/local/lib/python2.7/site-packages/circus/watcher.py", line 917, in call_hook
    result = self.hooks[hook_name](**hook_kwargs)
  File "/home/cory/src/Noms/hello.py", line 3, in hook
    print os.environ['hello_env']
  File "/home/cory/.virtualenvs/noms/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'hello_env'
2017-05-14 13:15:56 circus[22707] [INFO] Arbiter now waiting for commands
```

**Comment by corydodt** [comment]
I should add that hooks seem to _automatically_ inherit the process environment of circusd, which is troubling because this happens even with `copy_env:false`!

**Comment by meitham** [comment]
We have designed all our hooks to be part of the ``circusd`` env, rather than the various watchers virtualenvs, so I'm hoping this does not change, otherwise it will break our existing prodution code :-(

**Comment by k4nar** [comment]
As @meitham said this would be a breaking change. I'm not willing to do this as it would probably break more code than it would solve future issues.

If you need to access the watcher's defined env variable, you can use `watcher.env`.
