### ISSUE TITLE
Ubuntu  can't find chaussette

### ISSUE THREAD

**Issue by imarkzzz** [circus-tent/circus#1061]
Ubuntu 16.04, anaconda3, python 3.6.3
I follow the demo 
https://circus.readthedocs.io/en/latest/usecases/#running-a-wsgi-application
when I run it, I got

> circus[16522] [WARNING] error in 'webworker': [Errno 2] No such file or directory: 'chaussette': 'chaussette'

> but when I run chaussette, it is ok.

**Comment by imarkzzz** [comment]
When I run the demo
https://circus.readthedocs.io/en/latest/tutorial/step-by-step/#examples
I got 
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/anaconda3/lib/python3.6/site-packages/circusweb/circushttpd.py", line 25, in <module>
    import tornadio2
  File "/home/mark/anaconda3/lib/python3.6/site-packages/tornadio2/__init__.py", line 25, in <module>
    from tornadio2.router import TornadioRouter
  File "/home/mark/anaconda3/lib/python3.6/site-packages/tornadio2/router.py", line 27, in <module>
    from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
  File "/home/mark/anaconda3/lib/python3.6/site-packages/tornadio2/persistent.py", line 143
    except Exception, ex:
                    ^
SyntaxError: invalid syntax

error code is :
circus[17093] [INFO] Arbiter exiting

**Comment by biozz** [comment]
Hi @imarkzzz!

When properly installed, `chausette` is just another program in your system. Please make sure you can run it without circus and verify its location. Maybe it is not in your `PATH`.

The second error you posted is related to Python version. `Exception, ex` is from Python 2, and you are running Python 3, which uses `Exception as ex`. Please update circus and try again, because Python 3 is now fully supported.

Closing due to inactivity.
