### ISSUE TITLE
TypeError: constructor returned NULL 

### ISSUE THREAD

**Issue by Williamtsanga** [circus-tent/circus#1071]
from gi.repository import GLib , GObject
from multiprocessing import Pipe
parent,child = Pipe(duplex=False)
GObject.io_add_watch(parent.fileno() , GObject.IO_IN , myfonction )
 **_Then i get this error_**

Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.5\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\msys64\mingw64\lib\python3.5\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "mnG.py", line 1091, in <lambda>
    test = Thread(target=(lambda : GObject.io_add_watch(parant.fileno(), GObject.IO_IN, self.up)),name="GObject")
  File "C:\msys64\mingw64\lib\python3.5\site-packages\gi\overrides\GLib.py", line 749, in io_add_watch
    channel, priority, condition, func, user_data = _io_add_watch_get_args(*args, **kwargs)
  File "C:\msys64\mingw64\lib\python3.5\site-packages\gi\overrides\GLib.py", line 729, in _io_add_watch_get_args
    real_channel = GLib.IOChannel.unix_new(channel)
TypeError: constructor returned NULL

**_but this small code is working correctly on Linux (debian) 
Why ? how to hava a valide file descriptore from parant_**

**Comment by k4nar** [comment]
Are you sure this is linked to Circus? I don't know what `gi` is but I don't see anything related to Circus in your example :) .

**Comment by biozz** [comment]
Closing due to inactivity.

@Williamtsanga please feel free to reopen if the problem still exists. Please also provide more context with an example of actual circus usage.
