### ISSUE TITLE
socket.gaierror when specifying a custom syslog endpoint

### ISSUE THREAD

**Issue by MFlossmann** [circus-tent/circus#1159]
Hi! I encountered an error when trying to log to a custom syslog-port.

- Python: 3.8
- Circus-Version: `0.17.1`

# Steps to reproduce

Try to run the following `config.ini` with `circusd`:

``` config
[circus]
logoutput = syslog://localhost:5514?user

[watcher:dummy_watcher]
cmd = true
```

On my system, it raises an error with the following output:

```
Traceback (most recent call last):
  File "/home/MFlossmann/.local/bin/circusd", line 8, in <module>
    sys.exit(main())
  File "/home/MFlossmann/.local/lib/python3.8/site-packages/circus/circusd.py", line 146, in main
    configure_logger(logger, loglevel, logoutput, loggerconfig)
  File "/home/MFlossmann/.local/lib/python3.8/site-packages/circus/util.py", line 704, in configure_logger
    handler = logging.handlers.SysLogHandler(
  File "/usr/lib/python3.8/logging/handlers.py", line 829, in __init__
    ress = socket.getaddrinfo(host, port, 0, socktype)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 2115, in shutdown
    h.close()
  File "/usr/lib/python3.8/logging/handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'
```

This is due to a bug in [circus/util.py#700](https://github.com/circus-tent/circus/blob/master/circus/util.py#L700), where the address for the SysLogHandler is set to `(info.netlog, info.port or 514)` instead of `(info.hostname, info.port or 514)`. The current implementation results in the first element of the tuple becoming `hostname:port`, while `SysLogHandler` requires a tuple of the form `(hostname, port)`.

**Comment by biozz** [comment]
Resolved in  #1160
