### ISSUE TITLE
ConflictError arbiter is already running arbiter_start_watchers command

### ISSUE THREAD

**Issue by lovesharepc** [circus-tent/circus#1202]
hello I use ubuntu22.04 with python3.10.6
virsion
circus                 0.17.2
tornado                6.2
when I use start circusd to start my app get this error message 

```
2022-11-09 08:31:19 tornado.application[70459] [ERROR] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7fe6dfead960>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/usr/local/lib/python3.10/dist-packages/circus/util.py", line 1042, in wrapper
    raise ConflictError("arbiter is already running %s command"
circus.exc.ConflictError: arbiter is already running arbiter_start_watchers command
```

in ubuntu 20.04 with python3.8.10
virsion
circus                 0.17.1
tornado                6.2

there is no error like this 

how do I resolve this problem ?

**Comment by encetamasb** [comment]
I have the same issue.

I get this error only if I set numprocesses > 4 on my single watcher.

**Comment by thebaptiste** [comment]
Same issue here

**Comment by marcinbarczynski** [comment]
Same issue here. 

As a workaround during startup, you can increase `check_delay` to delay `manage_watchers` from starting. However, errors will also begin to show up when stopping, as demonstrated in the example below:

circus.ini:
```
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556

[watcher:worker]
cmd = uv run python
args = worker.py
numprocesses = 1
```

worker.py:
```
import signal
import time


shutdown_requested = False


def signal_handler(signum, frame):
    global shutdown_requested
    print(f"\n[Worker] Received signal {signum}, initiating graceful shutdown...")
    shutdown_requested = True


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, signal_handler)
    print("[Worker] Starting worker process...")
    iteration = 0
    while True:
        if shutdown_requested:
            print("[Worker] Shutdown requested, beginning 10-second cleanup...")
            for i in range(10, 0, -1):
                print(f"[Worker] Cleaning up... {i} seconds remaining")
                time.sleep(1)
            print("[Worker] Cleanup complete, exiting.")
            break
        iteration += 1
        print(f"[Worker] Working... iteration {iteration}")
        time.sleep(2)
```
Every `check_delay` = 5 seconds:
```
[Worker] Received signal 15, initiating graceful shutdown...
[Worker] Shutdown requested, beginning 10-second cleanup...
[Worker] Cleaning up... 10 seconds remaining
[Worker] Cleaning up... 9 seconds remaining
[Worker] Cleaning up... 8 seconds remaining
2025-12-17 13:32:47 tornado.application[1748994] [ERROR] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7cd0e7736690>>
Traceback (most recent call last):
  File "/home/q/dev/tmp/circ/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 945, in _run
    val = self.callback()
          ^^^^^^^^^^^^^^^
  File "/home/q/dev/tmp/circ/.venv/lib/python3.12/site-packages/circus/util.py", line 1042, in wrapper
    raise ConflictError("arbiter is already running %s command"
circus.exc.ConflictError: arbiter is already running watcher_stop command
[Worker] Cleaning up... 7 seconds remaining
[Worker] Cleaning up... 6 seconds remaining
[Worker] Cleaning up... 5 seconds remaining
[Worker] Cleaning up... 4 seconds remaining
[Worker] Cleaning up... 3 seconds remaining
2025-12-17 13:32:52 tornado.application[1748994] [ERROR] Exception in callback <bound method Arbiter.manage_watchers of <circus.arbiter.Arbiter object at 0x7cd0e7736690>>
Traceback (most recent call last):
  File "/home/q/dev/tmp/circ/.venv/lib/python3.12/site-packages/tornado/ioloop.py", line 945, in _run
    val = self.callback()
          ^^^^^^^^^^^^^^^
  File "/home/q/dev/tmp/circ/.venv/lib/python3.12/site-packages/circus/util.py", line 1042, in wrapper
    raise ConflictError("arbiter is already running %s command"
circus.exc.ConflictError: arbiter is already running watcher_stop command
[Worker] Cleaning up... 2 seconds remaining
```

I don't think it should generate a nasty traceback at the error level.

**Comment by marcinbarczynski** [comment]
This commit introduced a problem: https://github.com/circus-tent/circus/commit/1e35f5e59c9669622f3e5389802e2228f3df9d2b. Since then, the ConflictError is no longer being caught.
