### ISSUE TITLE
Issue with PyPy

### ISSUE THREAD

**Issue by k4nar** [circus-tent/circus#744]
Hello,
I have the following ini file : 

``` ini
[watcher:A]
cmd = echo "Hi, I'm A"
respawn = False

[watcher:B]
cmd = echo "Hi, I'm B"
respawn = False
```

With Python 2 and 3, I get an expected behavior : 

```
2014-03-07 22:17:56 [11563] [INFO] Starting master on pid 11563
Hi, I'm A
2014-03-07 22:17:56 [11563] [INFO] Arbiter now waiting for commands
2014-03-07 22:17:56 [11563] [INFO] A started
Hi, I'm B
2014-03-07 22:17:56 [11563] [INFO] B started
2014-03-07 22:18:01 [11563] [INFO] A stopped
2014-03-07 22:18:01 [11563] [INFO] B stopped
^C2014-03-07 22:18:05 [11563] [INFO] Got signal SIG_INT
2014-03-07 22:18:05 [11563] [INFO] Arbiter exiting
```

But with PyPy, I only have that : 

```
2014-03-07 22:21:10 [11719] [INFO] Starting master on pid 11719
Hi, I'm A
2014-03-07 22:21:10 [11719] [INFO] Arbiter now waiting for commands
```

Then, after a first SIGINT : 

```
^C2014-03-07 22:21:32 [11719] [INFO] Got signal SIG_INT
2014-03-07 22:21:32 [11719] [INFO] A started
```

After a second : 

```
^C2014-03-07 22:22:02 [11719] [INFO] Got signal SIG_INT
ERROR:tornado.application:Exception in callback <function wrapped at 0x0000000006cdb5b0>
Traceback (most recent call last):
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/ioloop.py", line 688, in start
    self._handlers[fd](fd, events)
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/stack_context.py", line 343, in _handle_exception
    if tail.exit(*exc):
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/stack_context.py", line 186, in exit
    return self.exception_handler(type, value, traceback)
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/gen.py", line 210, in handle_exception
    future.set_exc_info((typ, value, tb))
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/concurrent.py", line 125, in set_exc_info
    self.set_exception(exc_info[1])
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/concurrent.py", line 87, in set_exception
    self._set_done()
  File "/home/yannick/.virtualenvs/onitu-pypy/site-packages/tornado/concurrent.py", line 95, in _set_done
    for cb in self._callbacks:
TypeError: 'NoneType' object is not iterable
Hi, I'm B
```

And then I have the same TraceBack after each SIGINT.

I get the same behavior with the current master and the last release (0.10).

**Comment by k4nar** [comment]
Interestingly, I'm getting the exact same result than before with the current master, despite all the changes (Windows compatibility, Tornado 4…).

Is anyone ready to work on this?
