### ISSUE TITLE
tornado.application[2203] [ERROR] Exception in I/O handler for fd 23

### ISSUE THREAD

**Issue by gene1wood** [circus-tent/circus#755]
In our (Services Ops) release of circus : 697126ca573adb0f0edcd7ab264d675f7579ba6b

one of our two FxA auth servers is failing to route stdout and stderr for our circus managed process to the files that circus is supposed to write to.

The circus log is showing this exception about once a second

```
2014-03-31 20:45:22 tornado.application[2203] [ERROR] Exception in I/O handler for fd 23
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/tornado/ioloop.py", line 672, in start
    self._handlers[fd](fd, events)
  File "/usr/lib/python2.6/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/usr/lib/python2.6/site-packages/tornado/stack_context.py", line 343, in _handle_exception
    if tail.exit(*exc):
  File "/usr/lib/python2.6/site-packages/tornado/stack_context.py", line 186, in exit
    return self.exception_handler(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/tornado/gen.py", line 204, in handle_exception
    future.set_exc_info((typ, value, tb))
  File "/usr/lib/python2.6/site-packages/tornado/concurrent.py", line 125, in set_exc_info
    self.set_exception(exc_info[1])
  File "/usr/lib/python2.6/site-packages/tornado/concurrent.py", line 87, in set_exception
    self._set_done()
  File "/usr/lib/python2.6/site-packages/tornado/concurrent.py", line 95, in _set_done
    for cb in self._callbacks:
TypeError: 'NoneType' object is not iterable
```

cc @whd

**Comment by k4nar** [comment]
I'm closing this as it got no momentum for over two years. Feel free to open a new issue if you see something similar.
