### ISSUE TITLE
Python 3.4 — test_resource_watcher_min_mem fail and crashes

### ISSUE THREAD

**Issue by Natim** [circus-tent/circus#774]
```
==================================================================
ERROR: test_resource_watcher_min_mem (circus.tests.test_plugin_resource_watcher.TestResourceWatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/.tox/py34/lib/python3.4/site-packages/tornado/testing.py", line 427, in wrapper
    functools.partial(f, self), timeout=timeout)
  File "~/.tox/py34/lib/python3.4/site-packages/tornado/ioloop.py", line 388, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
nose.proxy.TimeoutError: Operation timed out after 30.0 seconds
-------------------- >> begin captured logging << --------------------
circus: INFO: Registering signals...
circus: INFO: Starting master on pid 7275
circus: WARNING: Multicast discovery is disabled, there was anerror during udp socket creation.
Traceback (most recent call last):
  File "~/circus/controller.py", line 61, in _init_multicast_endpoint
    multicast_port)
  File "~/.tox/py34/lib/python3.4/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "~/.tox/py34/lib/python3.4/site-packages/mock.py", line 1010, in _mock_call
    raise effect
OSError
circus: DEBUG: Initializing watchers
circus: DEBUG: cmd: ~/.tox/py34/bin/python
circus: DEBUG: args: ['generic.py', 'circus.tests.test_plugin_resource_watcher.run_leaky', '/tmp/tmpupap8hl6']
circus: DEBUG: process args: ['~/.tox/py34/bin/python', 'generic.py', 'circus.tests.test_plugin_resource_watcher.run_leaky', '/tmp/tmpupap8hl6']
circus: DEBUG: running test process [pid 7658]
circus: INFO: test started
circus: INFO: Arbiter now waiting for commands
circus: DEBUG: got message b'{"properties":{"name":"test"},"command":"stats"}'
circus: DEBUG: got message b'{"properties":{"name":"test"},"command":"stats"}'
circus: INFO: Arbiter exiting
circus: DEBUG: stopping the test watcher
circus: DEBUG: gracefully stopping processes [test] for 2.0s
circus: DEBUG: reaping already dead process 7658 [test]
circus: INFO: test stopped
circus: INFO: Arbiter exiting
--------------------- >> end captured logging << ---------------------

Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1295, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1058, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by k4nar** [comment]
I think #844 got it, I did not see this error since.
