### ISSUE TITLE
odd output from 'circusctl stats' on OSX

### ISSUE THREAD

**Issue by davidbirdsong** [circus-tent/circus#835]
Fresh install of Mavericks and fresh install of ```0.1.1.``` from pypi tarball, when I try to get stats about running watchers, I get output I can't figure out the meaning of:
```
(circusctl) stats
error: command '{"command":"stats","properties":{"extended":false},"id":"dc68c3e401524dd78d3ee7a50247d35f"}': (pid=62225)
```

Additionally, I noticed that running the stats endpoint causes weird permission errors.

```
2014-09-23 07:19:07 circus[65997] [ERROR] Failed to get info for 66085. (pid=66085)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/circus/stats/collector.py", line 75, in collect_stats
    info = util.get_info(pid)
  File "/usr/local/lib/python2.7/site-packages/circus/util.py", line 259, in get_info
    raw_cmdline = get_cmdline(process)
  File "/usr/local/lib/python2.7/site-packages/circus/process.py", line 85, in get_cmdline
    return proc.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 551, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 191, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: (pid=66085)
```

circusd is set to run as root.

OS version:  Darwin Kernel Version 13.1.0:

**Comment by k4nar** [comment]
Errors are catched now: http://github.com/circus-tent/circus/blob/83b2c8a4567477fa16c136abe82a03ff26fa756e/circus/stats/collector.py#L74-L85
