### ISSUE TITLE
ImportError: No module named concurrent

### ISSUE THREAD

**Issue by pyprism** [circus-tent/circus#865]
Circus isn't running , I am using ubuntu 12.04 . Here is the error code when I run `circusd` command  : 
```
Traceback (most recent call last):
  File "/usr/local/bin/circusd", line 9, in <module>
    load_entry_point('circus==0.11.1', 'console_scripts', 'circusd')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/circus/circusd.py", line 7, in <module>
    from circus.arbiter import Arbiter
  File "/usr/local/lib/python2.7/dist-packages/circus/arbiter.py", line 16, in <module>
    from circus.controller import Controller
  File "/usr/local/lib/python2.7/dist-packages/circus/controller.py", line 16, in <module>
    from tornado.concurrent import Future
ImportError: No module named concurrent
```

**Comment by k4nar** [comment]
Which version of Tornado do you have ? ATM circus requires Tornado >= 3.0 and < 4.0.
