### ISSUE TITLE
Tornado 4 support

### ISSUE THREAD

**Issue by k4nar** [circus-tent/circus#872]
We should support Tornado >= 4.0, which adds lots of improvements and bugfixes.

I tried to add it, but I'm getting some errors:

```
test_add_watcher (circus.tests.test_arbiter.TestArbiter) ... ok
test_start_arbiter_with_autostart (circus.tests.test_arbiter.TestArbiter) ... ok
test_start_watcher (circus.tests.test_arbiter.TestArbiter) ... ok
test_start_watchers_with_autostart (circus.tests.test_arbiter.TestArbiter) ... ok
test_circushttpd (circus.tests.test_arbiter.TestCircusWeb) ... SKIP: Tests for circus-web
test_add_watcher (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher1 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher2 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher4 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher5 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher6 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher7 (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher_already_exists (circus.tests.test_arbiter.TestTrainer) ... ok
test_add_watcher_arbiter_stopped (circus.tests.test_arbiter.TestTrainer) ... ok
test_numprocesses (circus.tests.test_arbiter.TestTrainer) ... ok
test_numwatchers (circus.tests.test_arbiter.TestTrainer) ... ok
test_processes (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload1 (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload2 (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload_sequential (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload_uppercase (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload_wid_1_worker (circus.tests.test_arbiter.TestTrainer) ... ok
test_reload_wid_4_workers (circus.tests.test_arbiter.TestTrainer) ... ok
test_rm_watcher (circus.tests.test_arbiter.TestTrainer) ... ok
test_rm_watcher_nostop (circus.tests.test_arbiter.TestTrainer) ... ok
test_stop_watchers (circus.tests.test_arbiter.TestTrainer) ... ok
test_stop_watchers3 (circus.tests.test_arbiter.TestTrainer) ... ok
test_watchers (circus.tests.test_arbiter.TestTrainer) ... ok
test_launch_cli (circus.tests.test_circusctl.CLITest) ... ok
test_add (circus.tests.test_circusctl.CommandlineTest) ... ok
test_add_start (circus.tests.test_circusctl.CommandlineTest) ... ok
test_help_for_add_command (circus.tests.test_circusctl.CommandlineTest) ... ok
test_help_invalid_command (circus.tests.test_circusctl.CommandlineTest) ... ok
test_help_switch_no_command (circus.tests.test_circusctl.CommandlineTest) ... ok
test_daemon (circus.tests.test_circusd.TestCircusd) ... SKIP: Only when Gevent is loaded
test_daemonize (circus.tests.test_circusd.TestCircusd) ... ok
test_main (circus.tests.test_circusd.TestCircusd) ... ok
test_maxfd (circus.tests.test_circusd.TestCircusd) ... ok
test_client (circus.tests.test_client.TestClient) ... ok
test_message_id (circus.tests.test_client.TestWithHook) ... ERROR
test_decr_proc (circus.tests.test_command_decrproc.DecrProcTest) ... ok
test_incr_proc (circus.tests.test_command_incrproc.IncrProcTest) ... ok
test_incr_proc_message (circus.tests.test_command_incrproc.IncrProcTest) ... ok
test_list_error (circus.tests.test_command_list.ListCommandTest) ... ok
test_list_processors (circus.tests.test_command_list.ListCommandTest) ... ok
test_list_watchers (circus.tests.test_command_list.ListCommandTest) ... ok
test_quit (circus.tests.test_command_quit.QuitTest) ... ok
test_set_args (circus.tests.test_command_set.SetTest) ... ok
test_set_stream (circus.tests.test_command_set.SetTest) ... ok
test_handler (circus.tests.test_command_signal.SignalCommandTest) ... ok
test_console_msg (circus.tests.test_command_stats.StatsCommandTest) ... ok
test_execute (circus.tests.test_command_stats.StatsCommandTest) ... ok
test_check_delay (circus.tests.test_config.TestConfig) ... ok
test_config_unexistant (circus.tests.test_config.TestConfig) ... ok
test_copy_env (circus.tests.test_config.TestConfig) ... ok
test_dashes (circus.tests.test_config.TestConfig) ... ok
https://github.com/circus-tent/circus/pull/473 ... ok
test_env_casesense (circus.tests.test_config.TestConfig) ... ok
test_env_everywhere (circus.tests.test_config.TestConfig) ... ok
test_env_section (circus.tests.test_config.TestConfig) ... ok
https://github.com/circus-tent/circus/pull/554 ... ok
test_hooks (circus.tests.test_config.TestConfig) ... ok
test_include_multiple_wildcards (circus.tests.test_config.TestConfig) ... ok
test_include_wildcards (circus.tests.test_config.TestConfig) ... ok
test_issue137 (circus.tests.test_config.TestConfig) ... ok
https://github.com/circus-tent/circus/pull/310 ... ok
test_issue395 (circus.tests.test_config.TestConfig) ... ok
test_issue567 (circus.tests.test_config.TestConfig) ... ok
https://github.com/circus-tent/circus/pull/665 ... ok
test_loglevel (circus.tests.test_config.TestConfig) ... ok
test_logoutput (circus.tests.test_config.TestConfig) ... ok
test_override (circus.tests.test_config.TestConfig) ... ok
test_pidfile (circus.tests.test_config.TestConfig) ... ok
test_plugin_priority (circus.tests.test_config.TestConfig) ... ok
test_socket_so_reuseport_no (circus.tests.test_config.TestConfig) ... ok
test_socket_so_reuseport_yes (circus.tests.test_config.TestConfig) ... ok
test_variables_everywhere (circus.tests.test_config.TestConfig) ... ok
test_virtualenv (circus.tests.test_config.TestConfig) ... ok
test_watcher_env_var (circus.tests.test_config.TestConfig) ... ok
test_watcher_graceful_timeout (circus.tests.test_config.TestConfig) ... ok
test_watcher_stop_signal (circus.tests.test_config.TestConfig) ... ok
test_add_job (circus.tests.test_controller.TestController) ... ok
test_multicast_ioerror (circus.tests.test_controller.TestController) ... ok
test_multicast_oserror (circus.tests.test_controller.TestController) ... ok
test_multicast_valueerror (circus.tests.test_controller.TestController) ... ok
test_env (circus.tests.test_convert_option.TestConvertOption) ... ok
test_hooks (circus.tests.test_convert_option.TestConvertOption) ... ok
test_stdout_and_stderr_stream (circus.tests.test_convert_option.TestConvertOption) ... ok
test_loggerconfig_default_ini (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_default_opt (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_ini_ini (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_ini_opt (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_json_ini (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_json_opt (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_yaml_ini (circus.tests.test_logging.TestLoggingConfig) ... ok
test_loggerconfig_yaml_opt (circus.tests.test_logging.TestLoggingConfig) ... ok
test_file_stream (circus.tests.test_papa_stream.TestPapaStream) ... ok
test_stream (circus.tests.test_papa_stream.TestPapaStream) ... ok
test_timed_rotating_file_stream (circus.tests.test_papa_stream.TestPapaStream) ... ok
test_watched_file_stream (circus.tests.test_papa_stream.TestPapaStream) ... ok
test_pidfile (circus.tests.test_pidfile.TestPidfile) ... ok
test_default_loop_rate (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_handle_recv_implemented (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_look_after_known_watcher_triggers_restart (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_look_after_new_watcher_does_not_restart (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ok
test_missing_watcher_gets_removed_from_plugin_dict (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_mtime_is_modified (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_non_default_loop_rate (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_not_modified (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_path_is_modified (circus.tests.test_plugin_command_reloader.TestCommandReloader) ... ok
test_above_max_retry_triggers_final_stop (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_below_max_retry_triggers_restart (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_beyond_window_resets_tries (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_default_config (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_minus_one_max_retry_triggers_restart (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_reap_message_calls_check (circus.tests.test_plugin_flapping.TestFlapping) ... ok
test_resource_watcher_max_cpu (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_resource_watcher_max_mem (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_resource_watcher_max_mem_abs (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_resource_watcher_min_cpu (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_resource_watcher_min_mem (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_resource_watcher_min_mem_abs (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_service_config_param_is_deprecated (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_watcher_config_param_is_required (circus.tests.test_plugin_resource_watcher.TestResourceWatcher) ... ok
test_full_stats (circus.tests.test_plugin_statsd.TestFullStats) ... ok
test_watchdog_discovery_found (circus.tests.test_plugin_watchdog.TestPluginWatchDog) ... ok
test_watchdog_discovery_not_found (circus.tests.test_plugin_watchdog.TestPluginWatchDog) ... ok
test_base (circus.tests.test_process.TestProcess) ... ok
test_comparison (circus.tests.test_process.TestProcess) ... ok
test_initgroups (circus.tests.test_process.TestProcess) ... ok
test_process_parameters (circus.tests.test_process.TestProcess) ... ok
test_rlimits (circus.tests.test_process.TestProcess) ... ok
test_streams (circus.tests.test_process.TestProcess) ... SKIP: Nose runs without -s
test_reload_addplugins (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_addsockets (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_addwatchers (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_changeplugins (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_changesockets (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_changewatchers (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_delplugins (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_delsockets (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_delwatchers (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_envdictparsed (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_ignorearbiterwatchers (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_numprocesses (circus.tests.test_reloadconfig.TestConfig) ... ok
test_watcher_names (circus.tests.test_reloadconfig.TestConfig) ... ok
test_dummy (circus.tests.test_runner.TestRunner) ... ok
test_handler (circus.tests.test_sighandler.TestSigHandler) ... ok
test_bind_to_interface (circus.tests.test_sockets.TestSockets) ... ok
test_inet6 (circus.tests.test_sockets.TestSockets) ... ok
When no proto in the config, the default (0) is used. ... ok
test_load_from_config_replace (circus.tests.test_sockets.TestSockets) ... ok
test_load_from_config_umask (circus.tests.test_sockets.TestSockets) ... ok
Unknown proto in the config raises an error. ... ok
test_manager (circus.tests.test_sockets.TestSockets) ... ok
test_reuseport_supported (circus.tests.test_sockets.TestSockets) ... ok
test_reuseport_unsupported (circus.tests.test_sockets.TestSockets) ... ok
test_set_inheritable (circus.tests.test_sockets.TestSockets) ... ok
test_socket (circus.tests.test_sockets.TestSockets) ... ok
test_unix_cleanup (circus.tests.test_sockets.TestSockets) ... ok
test_unix_socket (circus.tests.test_sockets.TestSockets) ... ok
test_handler (circus.tests.test_stats_client.TestStatsClient) ... ok
test_collector_aggregation (circus.tests.test_stats_collector.TestCollector) ... ok
test_collector_aggregation_when_unknown_values (circus.tests.test_stats_collector.TestCollector) ... ok
test_socketstats (circus.tests.test_stats_collector.TestCollector) ... ok
test_watcherstats (circus.tests.test_stats_collector.TestCollector) ... ok
test_publish (circus.tests.test_stats_publisher.TestStatsPublisher) ... ok
test_publish_reraise_zmq_errors (circus.tests.test_stats_publisher.TestStatsPublisher) ... ok
test_publish_silent_zmq_errors_when_socket_closed (circus.tests.test_stats_publisher.TestStatsPublisher) ... ok
test_get_all_pids (circus.tests.test_stats_streamer.TestStatsStreamer) ... ok
test_get_circus_pids (circus.tests.test_stats_streamer.TestStatsStreamer) ... ok
test_get_pids (circus.tests.test_stats_streamer.TestStatsStreamer) ... ok
test_get_pids_circus (circus.tests.test_stats_streamer.TestStatsStreamer) ... ok
test_remove_pid (circus.tests.test_stats_streamer.TestStatsStreamer) ... ok
test_color_selections (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_data_split_into_lines (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_data_with_extra_lines (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_random_colored_output (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_red_colored_output (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_time_formatting (circus.tests.test_stream.TestFancyStdoutStream) ... ok
test_data_split_into_lines (circus.tests.test_stream.TestFileStream) ... ok
test_data_with_extra_lines (circus.tests.test_stream.TestFileStream) ... ok
test_data_with_no_EOL (circus.tests.test_stream.TestFileStream) ... ok
test_time_formatting (circus.tests.test_stream.TestFileStream) ... ok
test_data_split_into_lines (circus.tests.test_stream.TestWatchedFileStream) ... ok
test_data_with_extra_lines (circus.tests.test_stream.TestWatchedFileStream) ... ok
test_data_with_no_EOL (circus.tests.test_stream.TestWatchedFileStream) ... ok
test_move_file (circus.tests.test_stream.TestWatchedFileStream) ... ok
test_time_formatting (circus.tests.test_stream.TestWatchedFileStream) ... ok
test_file_stream (circus.tests.test_stream.TestWatcher) ... ok
test_stream (circus.tests.test_stream.TestWatcher) ... ok
test_timed_rotating_file_stream (circus.tests.test_stream.TestWatcher) ... ok
test_watched_file_stream (circus.tests.test_stream.TestWatcher) ... ok
test_inherited (circus.tests.test_umask.UmaskTest) ... ok
test_set_before_launch (circus.tests.test_umask.UmaskTest) ... ok
test_set_by_arbiter (circus.tests.test_umask.UmaskTest) ... ok
test_bytes2human (circus.tests.test_util.TestUtil) ... ok
test_convert_opt (circus.tests.test_util.TestUtil) ... ok
test_get_info (circus.tests.test_util.TestUtil) ... ok
test_get_info_still_works_when_denied_access (circus.tests.test_util.TestUtil) ... ok
test_get_python_version (circus.tests.test_util.TestUtil) ... ok
test_human2bytes (circus.tests.test_util.TestUtil) ... ok
test_load_virtualenv (circus.tests.test_util.TestUtil) ... ok
test_negative_uid_gid (circus.tests.test_util.TestUtil) ... ok
test_parse_env_str (circus.tests.test_util.TestUtil) ... ok
test_replace_gnu_args (circus.tests.test_util.TestUtil) ... ok
test_to_gid_str (circus.tests.test_util.TestUtil) ... ok
test_to_uid (circus.tests.test_util.TestUtil) ... ok
test_to_uid_str (circus.tests.test_util.TestUtil) ... ok
test_to_uidgid (circus.tests.test_util.TestUtil) ... ok
test_tobool (circus.tests.test_util.TestUtil) ... ok
test_working_dir_return_pwd_when_paths_are_equals (circus.tests.test_util.TestUtil) ... ok
test_hooks (circus.tests.test_validate_option.TestValidateOption) ... ok
test_rlimit (circus.tests.test_validate_option.TestValidateOption) ... ok
test_stderr_stream (circus.tests.test_validate_option.TestValidateOption) ... ok
test_stdout_stream (circus.tests.test_validate_option.TestValidateOption) ... ok
test_uidgid (circus.tests.test_validate_option.TestValidateOption) ... ok
test_not_respawning (circus.tests.test_watcher.RespawnTest) ... ok
test_stopping_a_watcher_doesnt_spawn (circus.tests.test_watcher.RespawnTest) ... ok
test_arbiter_reference (circus.tests.test_watcher.TestWatcher) ... ok
test_decr_too_much (circus.tests.test_watcher.TestWatcher) ... ok
test_max_age (circus.tests.test_watcher.TestWatcher) ... ok
test_signal (circus.tests.test_watcher.TestWatcher) ... ok
test_stats (circus.tests.test_watcher.TestWatcher) ... ok
test_unexisting (circus.tests.test_watcher.TestWatcher) ... ok
test_after_signal (circus.tests.test_watcher.TestWatcherHooks) ... ERROR
test_after_spawn (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_spawn_failure (circus.tests.test_watcher.TestWatcherHooks) ... Exception ignored in: <generator object _test_hooks at 0x7fd394a65360>
RuntimeError: generator ignored GeneratorExit
ok
test_after_spawn_false (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_start (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_start_fails (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_start_false (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_stop (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_stop_fails (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_after_stop_false (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_signal (circus.tests.test_watcher.TestWatcherHooks) ... ERROR
test_before_spawn (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_spawn_failure (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_spawn_false (circus.tests.test_watcher.TestWatcherHooks) ... Exception ignored in: <generator object _test_hooks at 0x7fd394a32828>
RuntimeError: generator ignored GeneratorExit
ok
test_before_start (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_start_fails (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_start_false (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_stop (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_stop_fails (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_before_stop_false (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_extended_stats (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_missing_hook (circus.tests.test_watcher.TestWatcherHooks) ... ok
test_copy_env (circus.tests.test_watcher.TestWatcherInitialization) ... ok
test_copy_path (circus.tests.test_watcher.TestWatcherInitialization) ... ok
test_hook_in_PYTHON_PATH (circus.tests.test_watcher.TestWatcherInitialization) ... ok
test_venv (circus.tests.test_watcher.TestWatcherInitialization) ... ok
test_venv_py_ver (circus.tests.test_watcher.TestWatcherInitialization) ... :/home/yannick/Projects/circus:/home/yannick/Projects/circus/XYZ:/home/yannick/Projects/circus/circus/tests/venv/lib/pythonmy_py_ver/site-packages:/home/yannick/.virtualenvs/circus/lib/python34.zip:/home/yannick/.virtualenvs/circus/lib/python3.4:/home/yannick/.virtualenvs/circus/lib/python3.4/plat-linux:/home/yannick/.virtualenvs/circus/lib/python3.4/lib-dynload:/usr/lib64/python3.4:/usr/lib/python3.4:/usr/lib/python3.4/plat-linux:/home/yannick/.virtualenvs/circus/lib/python3.4/site-packagesok
test_venv_site_packages (circus.tests.test_watcher.TestWatcherInitialization) ... :/home/yannick/Projects/circus:/home/yannick/Projects/circus/circus/tests/venv/lib/python3.4/site-packages/pip-7.7-py3.4.egg:/home/yannick/Projects/circus/XYZ:/home/yannick/Projects/circus/circus/tests/venv/lib/python3.4/site-packages:/home/yannick/.virtualenvs/circus/lib/python34.zip:/home/yannick/.virtualenvs/circus/lib/python3.4:/home/yannick/.virtualenvs/circus/lib/python3.4/plat-linux:/home/yannick/.virtualenvs/circus/lib/python3.4/lib-dynload:/usr/lib64/python3.4:/usr/lib/python3.4:/usr/lib/python3.4/plat-linux:/home/yannick/.virtualenvs/circus/lib/python3.4/site-packagesok

======================================================================
ERROR: test_message_id (circus.tests.test_client.TestWithHook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 118, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 499, in post_coroutine
    self._test_generator.throw(e)
  File "/home/yannick/Projects/circus/circus/tests/test_client.py", line 102, in test_message_id
    resp = yield self.cli.call(msg)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 494, in post_coroutine
    timeout=timeout)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/ioloop.py", line 417, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
nose.proxy.TimeoutError: Operation timed out after 30.0 seconds
-------------------- >> begin captured logging << --------------------
circus: INFO: Registering signals...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_after_signal (circus.tests.test_watcher.TestWatcherHooks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 118, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 499, in post_coroutine
    self._test_generator.throw(e)
  File "/home/yannick/Projects/circus/circus/tests/test_watcher.py", line 522, in test_after_signal
    hook_kwargs_test_function=func)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 494, in post_coroutine
    timeout=timeout)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/ioloop.py", line 417, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
nose.proxy.TimeoutError: Operation timed out after 30.0 seconds
-------------------- >> begin captured logging << --------------------
circus: INFO: Registering signals...
circus: INFO: Starting master on pid 12032
circus: WARNING: Multicast discovery is disabled, there was anerror during udp socket creation.
Traceback (most recent call last):
  File "/home/yannick/Projects/circus/circus/controller.py", line 61, in _init_multicast_endpoint
    multicast_port)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/mock.py", line 1010, in _mock_call
    raise effect
OSError
circus: DEBUG: Initializing watchers
circus: DEBUG: cmd: /home/yannick/.virtualenvs/circus/bin/python3
circus: DEBUG: args: ['circus/tests/generic.py', 'circus.tests.support.run_process', '/tmp/tmp_8vjtsn2']
circus: DEBUG: process args: ['/home/yannick/.virtualenvs/circus/bin/python3', 'circus/tests/generic.py', 'circus.tests.support.run_process', '/tmp/tmp_8vjtsn2']
circus: DEBUG: running test process [pid 12437]
circus: INFO: test started
circus: INFO: Arbiter now waiting for commands
circus: DEBUG: got message b'{"command":"stop","id":"d23bb7b7afd44f458770dafd74c8fcde","properties":{"waiting":true,"name":"test"}}'
circus: DEBUG: stopping the test watcher
circus: DEBUG: gracefully stopping processes [test] for 2.0s
circus: DEBUG: test: kill process 12437
circus: DEBUG: sending signal 15 to 12437
circus: DEBUG: reaping already dead process 12437 [test]
circus: INFO: test stopped
circus: INFO: Arbiter exiting
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_before_signal (circus.tests.test_watcher.TestWatcherHooks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 118, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 499, in post_coroutine
    self._test_generator.throw(e)
  File "/home/yannick/Projects/circus/circus/tests/test_watcher.py", line 515, in test_before_signal
    hook_kwargs_test_function=func)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/testing.py", line 494, in post_coroutine
    timeout=timeout)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/tornado/ioloop.py", line 417, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
nose.proxy.TimeoutError: Operation timed out after 30.0 seconds
-------------------- >> begin captured logging << --------------------
circus: INFO: Registering signals...
circus: INFO: Starting master on pid 12032
circus: WARNING: Multicast discovery is disabled, there was anerror during udp socket creation.
Traceback (most recent call last):
  File "/home/yannick/Projects/circus/circus/controller.py", line 61, in _init_multicast_endpoint
    multicast_port)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/yannick/.virtualenvs/circus/lib/python3.4/site-packages/mock.py", line 1010, in _mock_call
    raise effect
OSError
circus: DEBUG: Initializing watchers
circus: DEBUG: cmd: /home/yannick/.virtualenvs/circus/bin/python3
circus: DEBUG: args: ['circus/tests/generic.py', 'circus.tests.support.run_process', '/tmp/tmpuylw2240']
circus: DEBUG: process args: ['/home/yannick/.virtualenvs/circus/bin/python3', 'circus/tests/generic.py', 'circus.tests.support.run_process', '/tmp/tmpuylw2240']
circus: DEBUG: running test process [pid 12447]
circus: INFO: test started
circus: INFO: Arbiter now waiting for commands
circus: DEBUG: got message b'{"command":"stop","id":"96a3602fcf064803b19fe9ddc69d8260","properties":{"waiting":true,"name":"test"}}'
circus: DEBUG: stopping the test watcher
circus: DEBUG: gracefully stopping processes [test] for 2.0s
circus: DEBUG: test: kill process 12447
circus: DEBUG: sending signal 15 to 12447
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 254 tests in 66.619s

FAILED (SKIP=3, errors=3)
```

**Comment by k4nar** [comment]
I fixed the failing tests in `test_watcher`.

For `circus.tests.test_client.TestWithHook:test_message_id`, it hasn't been launched since quite a long time as https://github.com/circus-tent/circus/commit/ba9d078e79a756aab4a307a338d054468f43b1a9 made it async but `@gen_test` wasn't added, so Tornado was skipping it.
Tornado 4.0 now fails when `@gen_test` is missing, but adding it wasn't enough as the test is now failing for another reason.

@tarekziade : Do you have any idea on how to fix this test ?

**Comment by k4nar** [comment]
Should we just ignore those failing tests (as they are also failing with Tornado 3.x) ?

I think that official Tornado 4 is a blocker for the much needed 0.12 release, so we should act upon it.

**Comment by josegonzalez** [comment]
I would ignore the failing tests - since they already fail - and make that a blocker for the next release instead.

**Comment by oglu** [comment]
I've been working a bit on `circus.tests.test_client.TestWithHook` and I have a bit of difficulty understanding what the test is testing, specifically this line 

            self.assertRaises(CallError, self.cli.call, make_message("stop"))

The way I see the test, everything has to run asynchronously. 

As the arbitrer does not run in an external process, the `time.sleep` in `long_hook` will result in the process sleeping, but it will not timeout the call (as soon as the sleep lapses we are back in the loop). 

To work with gen_test, the test has to be written in something like this 
```python
    @gen_test
    def test_message_id(self):
        hooks = {'before_stop': ('circus.tests.test_client.long_hook', False)}
        testfile, arbiter = self.run_with_hooks(hooks)
        yield arbiter.start()
        try:
            msg = make_message("numwatchers")
            resp = yield self.cli.call(msg)
            self.assertEqual(resp.get("numwatchers"), 1)

            # this should timeout
            self.assertRaises(CallError, self.cli.call, make_message("stop"))

            # and we should get back on our feet
            del arbiter.watchers[0].hooks['before_stop']

            while arbiter.watchers[0].status() != 'stopped':
                yield tornado_sleep(.1)

            resp = yield self.cli.call(make_message("numwatchers"))
            self.assertEqual(resp.get("numwatchers"), 1)
        finally:
            arbiter.stop()
```

**Comment by k4nar** [comment]
@oglu: If you can make a patch for that test I will be glad to merge it. However, if we don't find a solution soon we might just ditch those tests.

**Comment by oglu** [comment]
@k4nar I will re-write the test so that it checks whether the hook is called (I think that's the spirit of the test) and I'll make a PR

**Comment by k4nar** [comment]
Ok, now that the PR is merged I can rebase my Tornado 4 branch and try to see if everything is fine.
