### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'get_nice'

### ISSUE THREAD

**Issue by jeekajoo** [circus-tent/circus#879]
Hi,

I have a looping `AttributeError: 'Process' object has no attribute 'get_nice'` error.

version: 0.11.1
python: 2.7.3 (the one that comes with ubuntu precise)

conf (my conf.d is empty):
```javascript
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557
include_dir = /etc/circus/conf.d
loggerconfig = /etc/circus/logger.yaml
;debug = True

[plugin:flapping]
use = circus.plugins.flapping.Flapping
retry_in = 3
max_retry = 2
```

logs:
```javascript
circus - DEBUG - error: command '{"command":"dstats","properties":{},"id":"53d738bbd18443f2bd8602ccfff2a3fb"}': 'Process' object has no attribute 'get_nice'

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/circus/controller.py", line 202, in dispatch
    resp = cmd.execute(self.arbiter, properties)
  File "/usr/lib/python2.7/dist-packages/circus/commands/dstats.py", line 64, in execute
    return {'info': get_info(interval=0.01)}
  File "/usr/lib/python2.7/dist-packages/circus/util.py", line 253, in get_info
    info['nice'] = get_nice(process)
  File "/usr/lib/python2.7/dist-packages/circus/process.py", line 80, in get_nice
    return proc.get_nice()
AttributeError: 'Process' object has no attribute 'get_nice'

circus - DEBUG - got message {"command":"listsockets","properties":{},"id":"85d8dcfd243046048dbc33322cd32471"}
2015-02-23 18:01:03 circus[15053] [ERROR] Failed to get info for 15052. 'Process' object has no attribute 'get_nice'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/circus/stats/collector.py", line 75, in collect_stats
    info = util.get_info(pid)
  File "/usr/lib/python2.7/dist-packages/circus/util.py", line 253, in get_info
    info['nice'] = get_nice(process)
  File "/usr/lib/python2.7/dist-packages/circus/process.py", line 80, in get_nice
    return proc.get_nice()
AttributeError: 'Process' object has no attribute 'get_nice'
```
looks like the problem is on `circusd-stats` 

Thanks

**Comment by k4nar** [comment]
Do you know which version of psutil your are using (`pip show psutil`) ?

According to https://github.com/circus-tent/circus/blob/bb11d4eaa82efb7d79822197db1c73cae46f7138/circus/process.py#L76-L80, Circus 0.11.1 should be fine with psutil 1.x and 2.x, but maybe it doesn't work with older versions.

**Comment by jeekajoo** [comment]
psutil was installed as a debian package as it is a dependancy of circus (`python-psutil (>= 0.4)`)

so it installed this:
```
python-psutil 0.4.1-1ubuntu1
```

**Comment by k4nar** [comment]
Hum, I'm not sure where does this `>= 0.4` come from, but I'm pretty sure that you should use at least psutil `1.2.1`.

**Comment by jeekajoo** [comment]
`>= 0.4` comes from https://github.com/circus-tent/circus/blob/master/debian/control#L25

**Comment by k4nar** [comment]
Ok, I guess we should update the instructions for Debian some day. I never used them myself. cc @imankulov

**Comment by k4nar** [comment]
Thanks to @douardda, Debian packaging has been updated.

cf https://github.com/circus-tent/circus/blob/debian/debian/control#L32
