### ISSUE TITLE
Circus 0.11.1 step-by-step instructions not working

### ISSUE THREAD

**Issue by bcopy** [circus-tent/circus#890]
Salut,

I followed the step-by-step instructions at 
http://circus.readthedocs.org/en/0.11.1/tutorial/step-by-step/#examples
(Xubuntu 14.04 64 bits)
but the chaussette process refuses to start.

If I go to the circus web console, the webapp entry says it's stopped.
If I try to switch the status to activate it, I get the following exception stack :

```
Traceback (most recent call last):
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/web.py", line 1498, in future_complete
    f.result()
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/tmp/circus/local/lib/python2.7/site-packages/circusweb/circushttpd.py", line 240, in get
    redirect_url=self.reverse_url('index'))
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 194, in <lambda>
    future, lambda future: callback(future.result()))
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/tmp/circus/local/lib/python2.7/site-packages/circusweb/util.py", line 33, in run_command
    res = yield gen.Task(command, *args, **kwargs)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 194, in <lambda>
    future, lambda future: callback(future.result()))
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/tmp/circus/local/lib/python2.7/site-packages/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "/tmp/circus/local/lib/python2.7/site-packages/circusweb/controller.py", line 142, in switch_status
    res = yield gen.Task(self.client.call, msg)
AttributeError: 'Controller' object has no attribute 'client'
```

Any clue as to what I'm doing wrong ?

**Comment by Natim** [comment]
You should use the circus-web master.

**Comment by k4nar** [comment]
@bcopy : Could you try with Circus 0.13 and the last version of chaussette?
