### ISSUE TITLE
Python 3.4 erro: RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by abadger1406** [circus-tent/circus#891]
Another Python 3 error .... this is using 0.12.0 version of circus on
python 3.4.....

$ circus-top
Traceback (most recent call last):
  File "/home/dave/ap/bin/circus-top", line 9, in <module>
    load_entry_point('circus==0.12.0', 'console_scripts', 'circus-top')()
  File "/home/dave/ap/lib/python3.4/site-packages/circus-0.12.0-py3.4.egg/circus/stats/client.py",
line 255, in main
    for pid in filter(valid_pid, watchers[watcher]):
RuntimeError: dictionary changed size during iteration
(ap) dave@PenguinWee4:~/ap/ap/src$ circus-top
Traceback (most recent call last):
  File "/home/dave/ap/bin/circus-top", line 9, in <module>
    load_entry_point('circus==0.12.0', 'console_scripts', 'circus-top')()
  File "/home/dave/ap/lib/python3.4/site-packages/circus-0.12.0-py3.4.egg/circus/stats/client.py",
line 255, in main
    for pid in filter(valid_pid, watchers[watcher]):
RuntimeError: dictionary changed size during iteration
(ap) dave@PenguinWee4:~/ap/ap/src$ circus-top
Traceback (most recent call last):
  File "/home/dave/ap/bin/circus-top", line 9, in <module>
    load_entry_point('circus==0.12.0', 'console_scripts', 'circus-top')()
  File "/home/dave/ap/lib/python3.4/site-packages/circus-0.12.0-py3.4.egg/circus/stats/client.py",
line 255, in main
    for pid in filter(valid_pid, watchers[watcher]):
RuntimeError: dictionary changed size during iteration

**Comment by k4nar** [comment]
Thanks for the report, should be fixed now.

**Comment by abadger1406** [comment]
Thanks for fast turn around
