### ISSUE TITLE
except ImportError, e      is not correct syntax for python 3.4

### ISSUE THREAD

**Issue by abadger1406** [circus-tent/circus#894]
2015-05-13 19:25:53 circus[2614] [INFO] Starting master on pid 2614
2015-05-13 19:25:53 circus[2614] [INFO] sockets started
2015-05-13 19:25:53 circus[2614] [INFO] Arbiter now waiting for commands
2015-05-13 19:25:53 circus[2614] [INFO] web started
2015-05-13 19:25:53 circus[2614] [INFO] circusd-stats started
2015-05-13 19:25:53 circus[2614] [INFO] circushttpd started
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dave/ap/lib/python3.4/site-packages/circusweb/circushttpd.py", line 27
    except ImportError, e:

Think the syntax should be like:-

http://stackoverflow.com/questions/19142231/cassandra-file-cqlsh-line-95-except-importerror-e

**Comment by abadger1406** [comment]
Just downloaded latest circus...and installed..

git clone https://github.com/circus-tent/circus.git
cd circus
python setup.py installl


and my circus.ini file looks like....

more circus.ini 
[circus]
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557
statsd = True
httpd = True
httpd_host = localhost
httpd_port = 9090

[watcher:web]
cmd = /home/dave/ap/bin/chaussette --fd $(circus.sockets.web) ap.wsgi:application
use_sockets = True
numprocesses = 2

[socket:web]
host = 0.0.0.0
port = 9999

**Comment by k4nar** [comment]
This is an issue with circus-web, not circus.
