### ISSUE TITLE
circusd is not taking back processes from Papa

### ISSUE THREAD

**Issue by cgarciaarano** [circus-tent/circus#921]
Hi,

we're testing Papa process kernel==1.0.5 with circus==0.12.1 in a lab, using a redis server (not daemonized) as watcher. To ensure that the process is not interrupted, we're perfomring a `redis-bechmark -l`.

```ini
[watcher:redis]
cmd = redis-server
use_papa = True
active = True
numprocesses = 1
```

When we stop circus via upstart (`service circus stop`, I'm assuming it's sending `SIGTERM` to circusd), Papa takes as child the redis-server process. This is ok.

When we start again circusd, `circusctl status` shows that the watcher is `starting`, and has 0 processes, indefinetely. The logs throw this traceback:

```
2015-09-01 16:29:29 tornado.application[16683] [ERROR] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/circus/arbiter.py", line 648, in manage_watchers
    yield list_to_yield
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/circus/watcher.py", line 535, in manage_processes
    yield self.spawn_processes()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/circus/watcher.py", line 587, in spawn_processes
    self.spawn_process(i)
  File "/usr/local/lib/python2.7/dist-packages/circus/watcher.py", line 647, in spawn_process
    close_child_stderr=self.close_child_stderr)
  File "/usr/local/lib/python2.7/dist-packages/circus/papa_process_proxy.py", line 36, in __init__
    super(PapaProcessProxy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/circus/process.py", line 214, in __init__
    self.spawn()
  File "/usr/local/lib/python2.7/dist-packages/circus/papa_process_proxy.py", line 84, in spawn
    self._worker = PapaProcessWorker(self, p['pid'])
  File "/usr/local/lib/python2.7/dist-packages/circus/papa_process_proxy.py", line 24, in __init__
    self._init(pid, _ignore_nsp=True)
AttributeError: 'PapaProcessWorker' object has no attribute '_init'
```

**Comment by scottkmaxwell** [comment]
Papa has received very little attention on Python 2.7 so I'm not too surprised. I'll try to have a look shortly. It is probably something really simple having to do with Py2 vs. Py3 naming changes.

**Comment by scottkmaxwell** [comment]
What version of psutil are you running?

**Comment by cgarciaarano** [comment]
We have psutil==3.1.1.

We usually install circus with psutil==1.2.1 due to a bug when running `circusctl stats WATCHER`, but I should have upgraded circus and it's requirements at some point. Hope it helps.

Thanks

**Comment by scottkmaxwell** [comment]
Are you certain you were running 3.1.1 on the system where you had the problem? That method exists in psutil 2 & 3 but does not exist on 1.2.1. So I would expect this problem on 1.2.1 but not on 3.1.1.

**Comment by scottkmaxwell** [comment]
It looks like the _init semi-constructor method was added to psutil for release 2.0.0 so I am suspecting that is the problem.

**Comment by cgarciaarano** [comment]
I've done a fresh install and, of course, you're right.

It looks like `pip install --upgrade psutils` leave the old files installed. 

Thanks!

**Comment by scottkmaxwell** [comment]
I added a check so if calling _init fails, circus will indicate that your version of psutil is probably too old.
