### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by Johnathon332** [circus-tent/circus#981]
`ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/circus/arbiter.py", line 526, in start
    self.initialize()
  File "/usr/local/lib/python2.7/site-packages/circus/util.py", line 479, in _log
    return func(self, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/circus/arbiter.py", line 487, in initialize
    self.evpub_socket.bind(self.pubsub_endpoint)
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Address already in use
`

I have tried to use the arbiter class however not sure if I am doing this correctly, as I didn't fully understand the documentation.  I am trying to run python scripts and here is how I do it:

`iBus = get_arbiter([{"cmd": "python2.7 /pathfinder/IBus.py", "numprocesses": 1, "shell": True}])
try:
            iBus.start()
finally:
            iBus.stop()`

**Comment by k4nar** [comment]
If you really want to start four arbiters, you will have to define different endpoints for the controller, pubsb and the stats (by giving them as keyword arguments to the `get_arbiter()` function.

However, I'm pretty sure that you don't need to start 4 arbiters :) . Usually, a single arbiter is enough to manage as many watchers as you want. An arbiter is like an instance of `circusd`, this is a process managing all the sub-processes.

**Comment by Johnathon332** [comment]
@k4nar How would I go about doing this?  Do I basically add 4 dictionaries to the list?

**Comment by k4nar** [comment]
Could you give me some code snippet ? :)
If you want to create 4 arbiters, you have to call `get_arbiter()` 4 times with different values for `controller` and `pubsub_endpoint` (and maybe `stat_endpoint`).

But again, I'm pretty sure you don't need 4 arbiters, but 4 (or more) watchers instead.

**Comment by Johnathon332** [comment]
`iBus = {"cmd": "/usr/local/bin/python2.7 IBus.py", "numprocesses": 1}
        reg = {"cmd": "/usr/local/bin/python2.7 reg.py", "numprocesses": 1}
        alloc = {"cmd": "/usr/local/bin/python2.7 alloc.py", "numprocesses": 1}
        srv = {"cmd": "/usr/local/bin/python2.7 srv.py", "numprocesses": 1}
        listener = {"cmd": "/usr/local/bin/python2.7 listener.py", "numprocesses": 1}
        arbiter = get_arbiter([iBus, reg, alloc, srv, listener])
        try:
            arbiter.start()
        finally:
            arbiter.stop()`

**Comment by k4nar** [comment]
(I edit your message for formatting ;))

**Comment by k4nar** [comment]
May I ask why you're not using a configuration file and `circusd` (like all the examples in the doc) ? Circus can be used via the Python API, but it's definitively not the recommended way (and it's badly documented).

**Comment by Johnathon332** [comment]
because I am building an application in python and it seems that the API would help me alleviate a lot of the work that I need to do.  Rather than reinventing the wheel I thought I'd use the python API

**Comment by k4nar** [comment]
@Johnathon332 : Any update ? What error do you have with the snippet you provided?
